personal page Ahmed
BuidlGuidl/batch3.buidlguidl.com pull request #11
Opened 2024-03-07 11:28 UTC by Ahmedborwin

## Description

My personal page is added as per the instructions

## Additional Information

- [ X] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ X] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #{issue number}_

Dealing with issue 8

Your ENS/address: 0x5f2AF68dF96F3e58e1a243F4f83aD4f5D0Ca6029

2024-03-07 16:01 UTC, carletex requested changes
Thanks for this @Ahmedborwin !!

Left a few review comments

2024-03-07 16:01 UTC, carletex commented on packages/hardhat/deploy/00_deploy_your_contract.ts
Same here! 

> You don't want to commit this file in this PR

2024-03-07 16:01 UTC, carletex commented on packages/nextjs/app/builders/0x5f2AF68dF96F3e58e1a243F4f83aD4f5D0Ca6029/page.tsx
> +        <h2 text-xl font-semibold>
Not valid code. Missing `className`?

2024-03-07 16:01 UTC, carletex commented on packages/nextjs/app/builders/0x5f2AF68dF96F3e58e1a243F4f83aD4f5D0Ca6029/page.tsx
> +        <h2 text-xl font-semibold>
Same here!

2024-03-09 19:00 UTC, technophile-04 commented on packages/hardhat/contracts/CheckIn.sol
Could you please delete this file, We don't want merge this to `main` it was to supposed to be created only while tackling #9 and keeping it local

2024-03-09 19:02 UTC, technophile-04 commented on packages/hardhat/deploy/00_deploy_your_contract.ts
We don't need to update this file, could please just copy this file from `main` and paste it so that we don't see diff about this: 

https://github.com/BuidlGuidl/batch3.buidlguidl.com/blob/main/packages/hardhat/deploy/00_deploy_your_contract.ts

2024-03-09 19:07 UTC, Ahmedborwin commented on packages/hardhat/deploy/00_deploy_your_contract.ts
Hey [technophile-04](https://github.com/technophile-04) - sure but i am not sure how to. Should I delete from the main branch on my forked project then push again?

2024-03-09 19:11 UTC, technophile-04 commented on packages/hardhat/deploy/00_deploy_your_contract.ts
Just copy the contents of this whole file : https://github.com/BuidlGuidl/batch3.buidlguidl.com/blob/main/packages/hardhat/deploy/00_deploy_your_contract.ts

and paste it into your forked main 00_deploy… file 

and commit the changes

2024-03-09 19:24 UTC, Ahmedborwin commented on packages/hardhat/deploy/00_deploy_your_contract.ts
Hey - thank you! i think it's sorted now

2024-03-10 07:51 UTC, technophile-04 approved these changes
Thanks @Ahmedborwin looking good !!

2024-03-10 07:57 UTC, merged